In [1]:
import pandas as pd

In [5]:
df = pd.read_excel("../data/raw/Saudi_Beverage_Sales_Synthetic_Dataset (1).xlsx")

In [6]:
df.shape

(20000, 17)

In [7]:
df.columns.tolist()

['Order_ID',
 'Date',
 'Region',
 'City',
 'Sales_Channel',
 'Retailer',
 'Brand',
 'Product',
 'Category',
 'Package_Size_ml',
 'Units_Sold',
 'Unit_Price_SAR',
 'Unit_Cost_SAR',
 'Revenue_SAR',
 'Cost_SAR',
 'Profit_SAR',
 'Gross_Margin_Pct']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          20000 non-null  str
 1   Date              20000 non-null  datetime64[us]
 2   Region            20000 non-null  str
 3   City              20000 non-null  str
 4   Sales_Channel     20000 non-null  str
 5   Retailer          20000 non-null  str
 6   Brand             20000 non-null  str
 7   Product           20000 non-null  str
 8   Category          20000 non-null  str
 9   Package_Size_ml   20000 non-null  int64
 10  Units_Sold        20000 non-null  int64
 11  Unit_Price_SAR    20000 non-null  float64
 12  Unit_Cost_SAR     20000 non-null  float64
 13  Revenue_SAR       20000 non-null  float64
 14  Cost_SAR          20000 non-null  float64
 15  Profit_SAR        20000 non-null  float64
 16  Gross_Margin_Pct  20000 non-null  float64
dtypes: datetime64[us](1), float64(6), int64(2), str(8)
memory usage: 2.6 MB

In [9]:
df["Order_ID"].duplicated().sum()

np.int64(0)

In [10]:
revenue_check = (
    df["Units_Sold"] * df["Unit_Price_SAR"]
).round(2)

(revenue_check != df["Revenue_SAR"]).sum()

np.int64(0)

In [11]:
cost_check = (
    df["Units_Sold"] * df["Unit_Cost_SAR"]
).round(2)

(cost_check != df["Cost_SAR"]).sum()

np.int64(0)

In [12]:
profit_check = (
    df["Revenue_SAR"] - df["Cost_SAR"]
).round(2)

(profit_check != df["Profit_SAR"]).sum()

np.int64(0)

In [13]:
margin_check = (
    (df["Profit_SAR"] / df["Revenue_SAR"]) * 100
).round(2)

(margin_check != df["Gross_Margin_Pct"]).sum()

np.int64(0)

In [14]:
df["Brand"].value_counts()

Brand
Kinza           4219
Pepsi           3905
Coca-Cola       3204
Mirinda         2726
7UP             2037
Sprite          1612
Mountain Dew    1511
Fanta            786
Name: count, dtype: int64

In [15]:
df["Region"].value_counts()

Region
Makkah              7041
Riyadh              4647
Eastern Province    3702
Madinah             1603
Asir                1178
Jazan               1045
Tabuk                784
Name: count, dtype: int64

In [16]:
df["Sales_Channel"].value_counts()

Sales_Channel
Hypermarket          5624
Supermarket          5502
Convenience Store    3605
Wholesale            2964
E-commerce           2305
Name: count, dtype: int64

In [17]:
df["City"].value_counts()

City
Riyadh    4647
Jeddah    4058
Dammam    2343
Mecca     1730
Medina    1603
Khobar    1359
Taif      1253
Abha      1178
Jazan     1045
Tabuk      784
Name: count, dtype: int64

In [18]:
df[["Units_Sold", "Revenue_SAR", "Cost_SAR", "Profit_SAR", "Gross_Margin_Pct"]].sum()

Units_Sold           8359569.00
Revenue_SAR         22204135.22
Cost_SAR            13021173.03
Profit_SAR           9182962.19
Gross_Margin_Pct      845790.12
dtype: float64

In [19]:
overall_margin = (
    df["Profit_SAR"].sum() / df["Revenue_SAR"].sum()
) * 100

overall_margin

np.float64(41.35699093441209)

In [20]:
brand_performance = (
    df.groupby("Brand")
      .agg(
          Transactions=("Order_ID", "count"),
          Units_Sold=("Units_Sold", "sum"),
          Revenue_SAR=("Revenue_SAR", "sum"),
          Profit_SAR=("Profit_SAR", "sum")
      )
      .sort_values("Revenue_SAR", ascending=False)
)

brand_performance

              Transactions  Units_Sold  Revenue_SAR  Profit_SAR
Brand
Pepsi                 3905     1618995   4392484.90  1804090.56
Kinza                 4219     1764298   4337895.38  1759511.55
Coca-Cola             3204     1343586   3638949.32  1475637.27
Mirinda               2726     1140622   3085945.01  1335166.40
7UP                   2037      854502   2307903.18   977931.00
Sprite                1612      677488   1840213.56   778025.99
Mountain Dew          1511      636394   1724356.33   681167.66
Fanta                  786      323684    876387.54   371431.76

In [22]:
brand_performance["Gross_Margin_Pct"] = (
    brand_performance["Profit_SAR"] /
    brand_performance["Revenue_SAR"] * 100
).round(2)

brand_performance.sort_values("Gross_Margin_Pct", ascending=False)

,Transactions,Units_Sold,Revenue_SAR,Profit_SAR,Gross_Margin_Pct
Brand,,,,,
Mirinda,2726,1140622,3085945.01,1335166.40,43.27
Fanta,786,323684,876387.54,371431.76,42.38
7UP,2037,854502,2307903.18,977931.00,42.37
Sprite,1612,677488,1840213.56,778025.99,42.28
Pepsi,3905,1618995,4392484.90,1804090.56,41.07
Kinza,4219,1764298,4337895.38,1759511.55,40.56
Coca-Cola,3204,1343586,3638949.32,1475637.27,40.55
Mountain Dew,1511,636394,1724356.33,681167.66,39.50

In [23]:
region_performance = (
    df.groupby("Region")
      .agg(
          Transactions=("Order_ID", "count"),
          Units_Sold=("Units_Sold", "sum"),
          Revenue_SAR=("Revenue_SAR", "sum"),
          Profit_SAR=("Profit_SAR", "sum")
      )
)

region_performance["Gross_Margin_Pct"] = (
    region_performance["Profit_SAR"] /
    region_performance["Revenue_SAR"] * 100
).round(2)

region_performance.sort_values("Revenue_SAR", ascending=False)

,Transactions,Units_Sold,Revenue_SAR,Profit_SAR,Gross_Margin_Pct
Region,,,,,
Makkah,7041,2975682,7902287.54,3265653.27,41.33
Riyadh,4647,1931159,5128618.94,2121821.91,41.37
Eastern Province,3702,1550311,4115549.37,1699922.84,41.30
Madinah,1603,658057,1751706.74,725666.67,41.43
Asir,1178,480739,1276812.74,528920.31,41.43
Jazan,1045,443481,1176006.03,485083.53,41.25
Tabuk,784,320140,853153.86,355893.66,41.72

In [24]:
channel_performance = (
    df.groupby("Sales_Channel")
      .agg(
          Transactions=("Order_ID", "count"),
          Units_Sold=("Units_Sold", "sum"),
          Revenue_SAR=("Revenue_SAR", "sum"),
          Profit_SAR=("Profit_SAR", "sum")
      )
)

channel_performance["Gross_Margin_Pct"] = (
    channel_performance["Profit_SAR"] /
    channel_performance["Revenue_SAR"] * 100
).round(2)

channel_performance.sort_values("Revenue_SAR", ascending=False)

,Transactions,Units_Sold,Revenue_SAR,Profit_SAR,Gross_Margin_Pct
Sales_Channel,,,,,
Wholesale,2964,2379294,5862529.40,2160528.64,36.85
Supermarket,5502,2144079,5817302.72,2475999.79,42.56
Hypermarket,5624,2184487,5742433.14,2338407.08,40.72
Convenience Store,3605,900654,2685223.79,1282544.17,47.76
E-commerce,2305,751055,2096646.17,925482.51,44.14

In [25]:
monthly_performance = (
    df.assign(Month=df["Date"].dt.to_period("M").astype(str))
      .groupby("Month")
      .agg(
          Transactions=("Order_ID", "count"),
          Units_Sold=("Units_Sold", "sum"),
          Revenue_SAR=("Revenue_SAR", "sum"),
          Profit_SAR=("Profit_SAR", "sum")
      )
)

monthly_performance["Gross_Margin_Pct"] = (
    monthly_performance["Profit_SAR"] /
    monthly_performance["Revenue_SAR"] * 100
).round(2)

monthly_performance

         Transactions  Units_Sold  Revenue_SAR  Profit_SAR  Gross_Margin_Pct
Month
2025-01           939      403464   1068259.69   441851.37             41.36
2025-02           922      379175   1003768.31   412995.37             41.14
2025-03          1055      443277   1179704.63   488967.97             41.45
2025-04           951      398663   1055530.19   433732.68             41.09
2025-05           993      427079   1127856.60   463211.14             41.07
2025-06          1072      434691   1161591.00   484587.64             41.72
2025-07          1061      441504   1174065.09   486798.69             41.46
2025-08          1009      408475   1083743.76   448074.34             41.35
2025-09           781      325255    860337.74   353243.36             41.06
2025-10           809      351770    934838.29   385503.27             41.24
2025-11           833      332605    885673.91   365557.23             41.27
2025-12           849      355815    947284.09   391675.02             41.35
2026-01           922      382990   1016159.26   420450.79             41.38
2026-02           934      401007   1067019.38   443455.03             41.56
2026-03          1063      451409   1195056.20   493035.46             41.26
2026-04           998      423470   1127484.81   466976.94             41.42
2026-05           994      406447   1082908.09   450985.56             41.65
2026-06          1058      428820   1141901.74   473925.04             41.50
2026-07          1007      422866   1127176.81   468000.03             41.52
2026-08           979      413091   1094931.45   450983.21             41.19
2026-09           771      327696    868844.18   358952.05             41.31

In [26]:
kpi_summary = pd.DataFrame({
    "Metric": [
        "Total Transactions",
        "Total Units Sold",
        "Total Revenue (SAR)",
        "Total Cost (SAR)",
        "Total Profit (SAR)",
        "Overall Gross Margin (%)"
    ],
    "Value": [
        len(df),
        df["Units_Sold"].sum(),
        df["Revenue_SAR"].sum(),
        df["Cost_SAR"].sum(),
        df["Profit_SAR"].sum(),
        round(df["Profit_SAR"].sum() / df["Revenue_SAR"].sum() * 100, 2)
    ]
})

kpi_summary

                     Metric        Value
0        Total Transactions     20000.00
1          Total Units Sold   8359569.00
2       Total Revenue (SAR)  22204135.22
3          Total Cost (SAR)  13021173.03
4        Total Profit (SAR)   9182962.19
5  Overall Gross Margin (%)        41.36

In [27]:
df[[
    "Units_Sold",
    "Unit_Price_SAR",
    "Unit_Cost_SAR",
    "Revenue_SAR",
    "Cost_SAR",
    "Profit_SAR",
    "Gross_Margin_Pct"
]].describe()

,Units_Sold,Unit_Price_SAR,Unit_Cost_SAR,Revenue_SAR,Cost_SAR,Profit_SAR,Gross_Margin_Pct
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,417.978450,2.709936,1.557758,1110.206761,651.058652,459.148110,42.289506
std,314.568062,0.195644,0.066834,789.788356,491.139133,305.183796,3.871737
min,24.000000,2.210000,1.390000,66.240000,36.480000,29.760000,30.740000
25%,218.000000,2.580000,1.510000,599.922500,337.550000,256.510000,39.700000
50%,331.000000,2.710000,1.570000,900.240000,516.105000,380.760000,42.210000
75%,516.000000,2.820000,1.610000,1373.452500,802.705000,570.025000,44.910000
max,5012.000000,3.150000,1.700000,12780.600000,8169.560000,4611.040000,52.870000

In [28]:
cleaned_df = df.copy()

cleaned_df = cleaned_df.sort_values(
    ["Date", "Order_ID"]
).reset_index(drop=True)

cleaned_df.head()

,Order_ID,Date,Region,City,Sales_Channel,Retailer,Brand,Product,Category,Package_Size_ml,Units_Sold,Unit_Price_SAR,Unit_Cost_SAR,Revenue_SAR,Cost_SAR,Profit_SAR,Gross_Margin_Pct
0,ORD000005,2025-01-01,Makkah,Jeddah,Hypermarket,Panda,Coca-Cola,Coca-Cola,Cola,330,171,2.63,1.64,449.73,280.44,169.29,37.64
1,ORD001476,2025-01-01,Makkah,Jeddah,Convenience Store,Aldrees,Pepsi,Pepsi,Cola,330,345,3.10,1.60,1069.50,552.00,517.50,48.39
2,ORD002723,2025-01-01,Eastern Province,Khobar,Wholesale,Al Othaim Wholesale,Pepsi,Pepsi,Cola,330,873,2.58,1.62,2252.34,1414.26,838.08,37.21
3,ORD002736,2025-01-01,Madinah,Medina,Supermarket,BinDawood,Sprite,Sprite,Lemon-Lime,330,619,2.85,1.52,1764.15,940.88,823.27,46.67
4,ORD003819,2025-01-01,Makkah,Jeddah,Supermarket,Tamimi Markets,Kinza,Kinza Cola,Cola,330,164,2.52,1.51,413.28,247.64,165.64,40.08

In [29]:
cleaned_df.to_csv(
    "../data/cleaned/Saudi_Beverage_Sales_Cleaned.csv",
    index=False
)